### ISSUE TITLE
Java-based packages broken

### ISSUE THREAD

**Issue by IainNZ** [JuliaCI/PackageEvaluator.jl#81]
@aviks how do I set the environment variables/install things so Java packages work?

**Comment by aviks** [comment]
On an Ubuntu server, the easiest way to install java is as follows. You must do this in the image, rather than at test time, since Oracle insist you click and accept their license. 

```
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
```

```
sudo apt-get install oracle-java7-installer
```
This last step will require a manual input for a click-thru license. 

One this is done, you can check the install location by:
```
sudo update-alternatives --config java
```

The base path returned by the above command must be set as the environment variable `JAVA_HOME`

On my `trusty` machine, I have `JAVA_HOME=/usr/lib/jvm/java-7-oracle` . You should most likely have the same. 

Glad to help if you have any questions.

**Comment by IainNZ** [comment]
Looks like I can get past the click:
http://stackoverflow.com/questions/19275856/auto-yes-to-the-license-agreement-on-sudo-apt-get-y-install-oracle-java7-instal

I'll give it a go

**Comment by IainNZ** [comment]
Just tested it manually, works great. Tests pass on JavaCall.jl, haven't checked Taro.jl manually but we'll see.

**Comment by aviks** [comment]
Once you can do a `using JavaCall` successfully,  Taro should be fine. 

Thanks @IainNZ !

**Comment by tkelman** [comment]
This started failing again a few days ago, @aviks could you take a look?

**Comment by aviks** [comment]
Tony, has the VM configuration changed? It seems we cannot find the JVM any more. 

```
ERROR: LoadError: LoadError: InitError: Cannot find java library libjvm.so
Search Path:
   /home/vagrant/.julia/v0.5/JavaCall/test
   /usr/lib/jvm/java-7-oracle/jre/lib/amd64/server
   /usr/lib/jvm/java-7-oracle/jre/lib/server
```

Are there logs saved from the last successful run?  I have tagged a new release recently, not sure if that's relevant. 

remind me where the image configuration is stored?

**Comment by tkelman** [comment]
The relevant bit of code was added by Iain to close this issue in https://github.com/JuliaCI/PackageEvaluator.jl/commit/747da5739f6455e3440f1a47aa892689398befe1, what's changed is that has started failing. We don't publicly update the logs from setup.sh running, but I can gist one for you. A few days ago when this started, the `oracle-java7-installer` failing to finish (it's a download failure, I think it was a 404 on some oracle url) left apt-get in a messed-up state so every other package that tried to use apt-get was breaking. I put a band-aid on that with 2ab61989aa9d75c06da8e4ac8dc46f2736c37e0b so at least the java package rolls back if it fails, so the java packages are still broken but the rest of the apt-get ones are okay.

**Comment by tkelman** [comment]
setup.sh log: https://gist.github.com/e844fb848f59744f04115270109aad81

relevant part
```
==> halfAK05: Reading package lists...
==> halfAK05: Building dependency tree...
==> halfAK05: 
==> halfAK05: Reading state information...
==> halfAK05: The following extra packages will be installed:
==> halfAK05:   java-common
==> halfAK05: Suggested packages:
==> halfAK05:   default-jre equivs binfmt-support visualvm ttf-baekmuk ttf-unfonts
==> halfAK05:   ttf-unfonts-core ttf-kochi-gothic ttf-sazanami-gothic ttf-kochi-mincho
==> halfAK05:   ttf-sazanami-mincho ttf-arphic-uming firefox firefox-2 iceweasel
==> halfAK05:   mozilla-firefox iceape-browser mozilla-browser epiphany-gecko
==> halfAK05:   epiphany-webkit epiphany-browser galeon midbrowser moblin-web-browser
==> halfAK05:   xulrunner xulrunner-1.9 konqueror chromium-browser midori google-chrome
==> halfAK05: Recommended packages:
==> halfAK05:   gsfonts-x11
==> halfAK05: The following NEW packages will be installed:
==> halfAK05:   java-common oracle-java7-installer
==> halfAK05: 0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
==> halfAK05: Need to get 152 kB of archives.
==> halfAK05: After this operation, 426 kB of additional disk space will be used.
==> halfAK05: Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main java-common all 0.51 [130 kB]
==> halfAK05: Get:2 http://ppa.launchpad.net/webupd8team/java/ubuntu/ trusty/main oracle-java7-installer all 7u80+7u60arm-0~webupd8~1 [22.4 kB]
==> halfAK05: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> halfAK05: Fetched 152 kB in 3s (46.2 kB/s)
==> halfAK05: Selecting previously unselected package java-common.
==> halfAK05: (Reading database ... 72907 files and directories currently installed.)
==> halfAK05: Preparing to unpack .../java-common_0.51_all.deb ...
==> halfAK05: Unpacking java-common (0.51) ...
==> halfAK05: Selecting previously unselected package oracle-java7-installer.
==> halfAK05: Preparing to unpack .../oracle-java7-installer_7u80+7u60arm-0~webupd8~1_all.deb ...
==> halfAK05: oracle-license-v1-1 license has already been accepted
==> halfAK05: Unpacking oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...
==> halfAK05: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> halfAK05: Processing triggers for mime-support (3.54ubuntu1.1) ...
==> halfAK05: Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
==> halfAK05: Setting up java-common (0.51) ...
==> halfAK05: Setting up oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...
==> halfAK05: Downloading Oracle Java 7...
==> halfAK05: --2017-05-27 04:33:39--  http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
==> halfAK05: Resolving download.oracle.com (download.oracle.com)... 
==> halfAK05: 207.210.142.170, 207.210.142.169
==> halfAK05: Connecting to download.oracle.com (download.oracle.com)|207.210.142.170|:80... 
==> halfAK05: connected.
==> halfAK05: HTTP request sent, awaiting response... 
==> halfAK05: 302 Moved Temporarily
==> halfAK05: Location: https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz [following]
==> halfAK05: --2017-05-27 04:33:39--  https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
==> halfAK05: Resolving edelivery.oracle.com (edelivery.oracle.com)... 
==> halfAK05: 104.96.204.183, 2600:1400:d:185::2d3e, 2600:1400:d:181::2d3e
==> halfAK05: Connecting to edelivery.oracle.com (edelivery.oracle.com)|104.96.204.183|:443... 
==> halfAK05: connected.
==> halfAK05: HTTP request sent, awaiting response... 
==> halfAK05: 302 Moved Temporarily
==> halfAK05: Location: http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1495859739_c97f7373fad95af14023ccc90b68e36e [following]
==> halfAK05: --2017-05-27 04:33:39--  http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1495859739_c97f7373fad95af14023ccc90b68e36e
==> halfAK05: Connecting to download.oracle.com (download.oracle.com)|207.210.142.170|:80... 
==> halfAK05: connected.
==> halfAK05: HTTP request sent, awaiting response... 
==> halfAK05: 404 Not Found
==> halfAK05: 2017-05-27 04:33:40 ERROR 404: Not Found.
==> halfAK05: download failed
==> halfAK05: Oracle JDK 7 is NOT installed.
==> halfAK05: dpkg: error processing package oracle-java7-installer (--configure):
==> halfAK05:  subprocess installed post-installation script returned error exit status 1
==> halfAK05: Errors were encountered while processing:
==> halfAK05:  oracle-java7-installer
==> halfAK05: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> halfAK05: Reading package lists...
==> halfAK05: Building dependency tree...
==> halfAK05: 
==> halfAK05: Reading state information...
==> halfAK05: The following package was automatically installed and is no longer required:
==> halfAK05:   java-common
==> halfAK05: Use 'apt-get autoremove' to remove it.
==> halfAK05: The following packages will be REMOVED:
==> halfAK05:   oracle-java7-installer
==> halfAK05: 0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
==> halfAK05: 1 not fully installed or removed.
==> halfAK05: After this operation, 127 kB disk space will be freed.
==> halfAK05: (Reading database ... 72979 files and directories currently installed.)
==> halfAK05: Removing oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...
==> halfAK05: Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
==> halfAK05: Processing triggers for mime-support (3.54ubuntu1.1) ...
==> halfAK05: Reading package lists...
==> halfAK05: Building dependency tree...
==> halfAK05: 
==> halfAK05: Reading state information...
==> halfAK05: The following package was automatically installed and is no longer required:
==> halfAK05:   java-common
==> halfAK05: Use 'apt-get autoremove' to remove it.
```

the removal is that new bit I added - I hope the way I wrote that, if the 404 weren't happening then it wouldn't try to remove it.

**Comment by aviks** [comment]
Thanks. Let's get rid of all of this, and install openjdk-8 directly from
apt. That should work now.

On 27 May 2017 11:59 am, "Tony Kelman" <notifications@github.com> wrote:

setup.sh log: https://gist.github.com/e844fb848f59744f04115270109aad81

relevant part

==> halfAK05: Reading package lists...
==> halfAK05: Building dependency tree...
==> halfAK05:
==> halfAK05: Reading state information...
==> halfAK05: The following extra packages will be installed:
==> halfAK05:   java-common
==> halfAK05: Suggested packages:
==> halfAK05:   default-jre equivs binfmt-support visualvm ttf-baekmuk
ttf-unfonts
==> halfAK05:   ttf-unfonts-core ttf-kochi-gothic ttf-sazanami-gothic
ttf-kochi-mincho
==> halfAK05:   ttf-sazanami-mincho ttf-arphic-uming firefox firefox-2 iceweasel
==> halfAK05:   mozilla-firefox iceape-browser mozilla-browser epiphany-gecko
==> halfAK05:   epiphany-webkit epiphany-browser galeon midbrowser
moblin-web-browser
==> halfAK05:   xulrunner xulrunner-1.9 konqueror chromium-browser
midori google-chrome
==> halfAK05: Recommended packages:
==> halfAK05:   gsfonts-x11
==> halfAK05: The following NEW packages will be installed:
==> halfAK05:   java-common oracle-java7-installer
==> halfAK05: 0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
==> halfAK05: Need to get 152 kB of archives.
==> halfAK05: After this operation, 426 kB of additional disk space
will be used.
==> halfAK05: Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main
java-common all 0.51 [130 kB]
==> halfAK05: Get:2 http://ppa.launchpad.net/webupd8team/java/ubuntu/
trusty/main oracle-java7-installer all 7u80+7u60arm-0~webupd8~1 [22.4
kB]
==> halfAK05: dpkg-preconfigure: unable to re-open stdin: No such file
or directory
==> halfAK05: Fetched 152 kB in 3s (46.2 kB/s)
==> halfAK05: Selecting previously unselected package java-common.
==> halfAK05: (Reading database ... 72907 files and directories
currently installed.)
==> halfAK05: Preparing to unpack .../java-common_0.51_all.deb ...
==> halfAK05: Unpacking java-common (0.51) ...
==> halfAK05: Selecting previously unselected package oracle-java7-installer.
==> halfAK05: Preparing to unpack
.../oracle-java7-installer_7u80+7u60arm-0~webupd8~1_all.deb ...
==> halfAK05: oracle-license-v1-1 license has already been accepted
==> halfAK05: Unpacking oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...
==> halfAK05: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> halfAK05: Processing triggers for mime-support (3.54ubuntu1.1) ...
==> halfAK05: Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
==> halfAK05: Setting up java-common (0.51) ...
==> halfAK05: Setting up oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...
==> halfAK05: Downloading Oracle Java 7...
==> halfAK05: --2017-05-27 04:33:39--
http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
==> halfAK05: Resolving download.oracle.com (download.oracle.com)...
==> halfAK05: 207.210.142.170, 207.210.142.169
==> halfAK05: Connecting to download.oracle.com
(download.oracle.com)|207.210.142.170|:80...
==> halfAK05: connected.
==> halfAK05: HTTP request sent, awaiting response...
==> halfAK05: 302 Moved Temporarily
==> halfAK05: Location:
https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
[following]
==> halfAK05: --2017-05-27 04:33:39--
https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
==> halfAK05: Resolving edelivery.oracle.com (edelivery.oracle.com)...
==> halfAK05: 104.96.204.183, 2600:1400:d:185::2d3e, 2600:1400:d:181::2d3e
==> halfAK05: Connecting to edelivery.oracle.com
(edelivery.oracle.com)|104.96.204.183|:443...
==> halfAK05: connected.
==> halfAK05: HTTP request sent, awaiting response...
==> halfAK05: 302 Moved Temporarily
==> halfAK05: Location:
http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1495859739_c97f7373fad95af14023ccc90b68e36e
[following]
==> halfAK05: --2017-05-27 04:33:39--
http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1495859739_c97f7373fad95af14023ccc90b68e36e
==> halfAK05: Connecting to download.oracle.com
(download.oracle.com)|207.210.142.170|:80...
==> halfAK05: connected.
==> halfAK05: HTTP request sent, awaiting response...
==> halfAK05: 404 Not Found
==> halfAK05: 2017-05-27 04:33:40 ERROR 404: Not Found.
==> halfAK05: download failed
==> halfAK05: Oracle JDK 7 is NOT installed.
==> halfAK05: dpkg: error processing package oracle-java7-installer
(--configure):
==> halfAK05:  subprocess installed post-installation script returned
error exit status 1
==> halfAK05: Errors were encountered while processing:
==> halfAK05:  oracle-java7-installer
==> halfAK05: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> halfAK05: Reading package lists...
==> halfAK05: Building dependency tree...
==> halfAK05:
==> halfAK05: Reading state information...
==> halfAK05: The following package was automatically installed and is
no longer required:
==> halfAK05:   java-common
==> halfAK05: Use 'apt-get autoremove' to remove it.
==> halfAK05: The following packages will be REMOVED:
==> halfAK05:   oracle-java7-installer
==> halfAK05: 0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
==> halfAK05: 1 not fully installed or removed.
==> halfAK05: After this operation, 127 kB disk space will be freed.
==> halfAK05: (Reading database ... 72979 files and directories
currently installed.)
==> halfAK05: Removing oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...
==> halfAK05: Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
==> halfAK05: Processing triggers for mime-support (3.54ubuntu1.1) ...
==> halfAK05: Reading package lists...
==> halfAK05: Building dependency tree...
==> halfAK05:
==> halfAK05: Reading state information...
==> halfAK05: The following package was automatically installed and is
no longer required:
==> halfAK05:   java-common
==> halfAK05: Use 'apt-get autoremove' to remove it.

the removal is that new bit I added - I hope the way I wrote that, if the
404 weren't happening then it wouldn't try to remove it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JuliaCI/PackageEvaluator.jl/issues/81#issuecomment-304442201>,
or mute the thread

**Comment by tkelman** [comment]
On trusty? That's what we've been running, I wasn't planning on upgrading the VM's to 16.04 for a little while longer. Can you propose what changing to openjdk-8 would look like in setup.sh and I'll do a test run?

**Comment by tkelman** [comment]
Bump. Java-based packages are not getting regression testing in rc3 runs since the baseline fails too.

**Comment by tkelman** [comment]
re-fixed by https://github.com/JuliaCI/PackageEvaluator.jl/pull/167 hopefully, will see for sure tomorrow

**Comment by tkelman** [comment]
oddly still broken on julia 0.4, oh well https://pkg.julialang.org/logs/JavaCall_0.4.log

**Comment by aviks** [comment]
Strange, the logs seem unhelpful as well. I suppose we'll stop supporting 0.4 soon, so _c'est la vie_
